### PR TITLE
Add support for relative paths

### PR DESCRIPTION
**Pull request by jeffreyvanhees**
When using multi tenant apps and/or multiple domains, it's desirable to use relative paths instead of absolute. This PR allows us to disable absolute paths (in Ziggy) through the plugin options.

```js
createInertiaApp({
  setup({ el, app, props, plugin }) {
    createApp({ render: () => h(app, props) })
      .use(trail, { routes, absolute: false })
  }
})
```

It's still `true` by default so it won't break anything.

### CODE REVIEW

**Comment by Bosphoramus** [comment]
I also need this, would be cool, but maybe also as an option on the route() helper

**Comment by shayaulman** [comment]
@lepikhinb, is there a specific reason why this PR has not been merged yet?

**Comment by lepikhinb** [comment]
@jeffreyvanhees thank you and sorry for the delay!

**Comment by shayaulman** [comment]
@lepikhinb the current Ziggy version has a bug when `absolute: false` is applied that has been [fixed in a newer release](https://github.com/tighten/ziggy/releases/tag/v1.7.0), is it possible to upgrade the package to the latest version?

**Pull request merged**
